# Use an official Node.js runtime as the base image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json to the working directory
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of your application's source code to the container
COPY . .

# Build your React application
RUN npm run build

# Expose the port your React app will run on (adjust if needed)
EXPOSE 3001

# Define the command to run your React app in production
CMD [ "npm", "run", "start:prod" ]
