 # Use an official Node.js runtime as the base image
FROM node:18-alpine
# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

#Copy prisma
COPY prisma ./prisma/


# Install project dependencies
RUN npm install

# Copy the rest of your application's source code to the container
COPY . .

# Expose the port your Nest.js application will run on (adjust if needed)
EXPOSE 3000

RUN npm run build

# Define the command to start your Nest.js application
ENTRYPOINT ["/bin/sh", "init.sh"]
